name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: brew install ldid-procursus make dpkg

    - name: Compile
      run: gmake -j$(sysctl -n hw.ncpu) package

    - name: Move files
      run: |
        mkdir -p files
        mv jetsamctl* files

    - uses: actions/upload-artifact@v4
      with:
        name: Build Output
        path: files/
